import { db, Customers, Items } from "astro:db";

export default async function () {
  await db.insert(Customers).values([
    {
      id: "1",
      name: "Bastinkie Thomson",
      address: "372 Main St, Kramson, CA 00048 (Apt 2)",
      email: "bastinkie.thomson@example.com",
      phone: "006 400 0306",
    },
    {
      id: "2",
      name: "Mediphira Bailey",
      address: "15 Indian Hill Rd, Thozzt, CA 00080",
      email: "mediphira.bailey@example.com",
      phone: "050 200 2955",
    },
    {
      id: "3",
      name: "Martinhella Hemmings",
      address: "31 Holton St, Agaris, CA 00055",
      email: "martinhella.hemmings@example.com",
      phone: "001 403 3335",
    },
    {
      id: "4",
      name: "Marshallazora Marshall",
      address: "84 Deerfield Rd, Carclop, CA 00062",
      email: "marshallazora.marshall@example.com",
      phone: "603 405 1306",
    },
    {
      id: "5",
      name: "Anderlok Graham",
      address: "16 Alprilla Farm Rd, Grindycdonald, CA 00048",
      email: "anderlok.graham@example.com",
      phone: "500 330 3005",
    },
    {
      id: "6",
      name: "Cullran Dickens",
      address: "201 Concord Ln, Lilmoore, CA 00040",
      email: "cullran.dickens@example.com",
      phone: "610 056 1166",
    },
    {
      id: "7",
      name: "Helraham Dyer",
      address: "26 James St, Coonsteinia, CA 00015",
      email: "helraham.dyer@example.com",
      phone: "510 520 5304",
    },
    {
      id: "8",
      name: "Vargasalka Glover",
      address: "58 Chandler St, Drisconic, CA 00044",
      email: "vargasalka.glover@example.com",
      phone: "610 694 9414",
    },
    {
      id: "9",
      name: "Jamesorty Alsop",
      address: "46 Spindlewick Dr, Surli, CA 00062",
      email: "jamesorty.alsop@example.com",
      phone: "603 430 9300",
    },
    {
      id: "10",
      name: "Lewisflame White",
      address: "12 Thistle Ct, Whitestenchia, CA 00063",
      email: "lewisflame.white@example.com",
      phone: "001 316 6529",
    },
    {
      id: "11",
      name: "Yompson Rees",
      address: "53 Oakhill Ave, Saundersula, CA 00003",
      email: "yompson.rees@example.com",
      phone: "500 446 5500",
    },
    {
      id: "12",
      name: "Marflutter Forsyth",
      address: "32 Sherman St, Angerris, CA 00055",
      email: "marflutter.forsyth@example.com",
      phone: "013 340 0062",
    },
    {
      id: "13",
      name: "Suth Paterson",
      address: "2 Brown Terrace, Frankenphy, CA 00030 (Apt 1L)",
      email: "suth.paterson@example.com",
      phone: "610 300 0595",
    },
    {
      id: "14",
      name: "Elstewart Perstompa",
      address: "118 Newbury St, Pormane, CA 00016 (Apt 2)",
      email: "elstewart.perstompa@example.com",
      phone: "610 201 9140",
    },
    {
      id: "15",
      name: "Martinhella Hemmings",
      address: "15 Indian Hill Rd, Thozzt, CA 00080",
      email: "martinhella.hemmings@example.com",
      phone: "050 200 2955",
    },
    {
      id: "16",
      name: "Anderlok Graham",
      address: "16 Alprilla Farm Rd, Grindycdonald, CA 00048",
      email: "anderlok.graham@example.com",
      phone: "006 400 0306",
    },
  ]);

  await db.insert(Items).values([
    {
      id: "1",
      sku: "SKU001",
      name: "Item 1",
      desc: "Description for Item 1",
      price: 9.99,
    },
    {
      id: "2",
      sku: "SKU002",
      name: "Item 2",
      desc: "Description for Item 2",
      price: 19.99,
    },
    {
      id: "3",
      sku: "SKU003",
      name: "Item 3",
      desc: "Description for Item 3",
      price: 29.99,
    },
    {
      id: "4",
      sku: "SKU004",
      name: "Item 4",
      desc: "Description for Item 4",
      price: 39.99,
    },
    {
      id: "5",
      sku: "SKU005",
      name: "Item 5",
      desc: "Description for Item 5",
      price: 49.99,
    },
    {
      id: "6",
      sku: "SKU006",
      name: "Item 6",
      desc: "Description for Item 6",
      price: 59.99,
    },
    {
      id: "7",
      sku: "SKU007",
      name: "Item 7",
      desc: "Description for Item 7",
      price: 69.99,
    },
    {
      id: "8",
      sku: "SKU008",
      name: "Item 8",
      desc: "Description for Item 8",
      price: 79.99,
    },
    {
      id: "9",
      sku: "SKU009",
      name: "Item 9",
      desc: "Description for Item 9",
      price: 89.99,
    },
    {
      id: "10",
      sku: "SKU010",
      name: "Item 10",
      desc: "Description for Item 10",
      price: 99.99,
    },
  ]);
}
